<?php

declare(strict_types=1);

namespace PhpNpm\Tests\Lockfile;

use PHPUnit\Framework\TestCase;
use PhpNpm\Lockfile\YarnLockParser;

// LockfileException is defined in LockfileParser.php within the same namespace
// We import it explicitly for the test
require_once __DIR__ . '/../../src/Lockfile/LockfileParser.php';
use PhpNpm\Lockfile\LockfileException;

/**
 * Tests for the YarnLockParser class.
 */
class YarnLockParserTest extends TestCase
{
    private YarnLockParser $parser;

    protected function setUp(): void
    {
        $this->parser = new YarnLockParser();
    }

    // ===== isYarnLock Detection Tests =====

    public function testIsYarnLockWithValidContent(): void
    {
        $content = <<<YAML
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10
YAML;

        $this->assertTrue(YarnLockParser::isYarnLock($content));
    }

    public function testIsYarnLockWithMetadataOnly(): void
    {
        $content = <<<YAML
__metadata:
  version: 8
YAML;

        $this->assertTrue(YarnLockParser::isYarnLock($content));
    }

    public function testIsYarnLockWithJsonContent(): void
    {
        $content = '{"lockfileVersion": 3, "packages": {}}';

        $this->assertFalse(YarnLockParser::isYarnLock($content));
    }

    // ===== Basic Parsing Tests =====

    public function testParseSimpleYarnLock(): void
    {
        $content = <<<YAML
__metadata:
  version: 8
  cacheKey: 10

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10/abcdef123456
  languageName: node
  linkType: hard
YAML;

        $packageJson = [
            'name' => 'my-project',
            'version' => '1.0.0',
            'dependencies' => [
                'lodash' => '^4.17.0',
            ],
        ];

        $result = $this->parser->parse($content, $packageJson);

        $this->assertEquals('my-project', $result['name']);
        $this->assertEquals('1.0.0', $result['version']);
        $this->assertEquals(3, $result['lockfileVersion']);
        $this->assertArrayHasKey('packages', $result);
        $this->assertArrayHasKey('_yarn', $result);
    }

    public function testParseScopedPackage(): void
    {
        $content = <<<YAML
__metadata:
  version: 8

"@babel/core@npm:^7.0.0":
  version: 7.26.0
  resolution: "@babel/core@npm:7.26.0"
  dependencies:
    "@babel/parser": "npm:^7.26.0"
  checksum: 10/xyz789
  languageName: node
  linkType: hard
YAML;

        $packageJson = [
            'name' => 'project',
            'version' => '1.0.0',
            'dependencies' => [
                '@babel/core' => '^7.0.0',
            ],
        ];

        $result = $this->parser->parse($content, $packageJson);

        $this->assertArrayHasKey('packages', $result);
        // Should have at least the root package
        $this->assertArrayHasKey('', $result['packages']);
    }

    public function testParsePreservesMetadata(): void
    {
        $content = <<<YAML
__metadata:
  version: 8
  cacheKey: 10

"lodash@npm:^4.0.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  languageName: node
  linkType: hard
YAML;

        $result = $this->parser->parse($content, []);

        $this->assertArrayHasKey('_yarn', $result);
        $this->assertArrayHasKey('metadata', $result['_yarn']);
        $this->assertEquals(8, $result['_yarn']['metadata']['version']);
        $this->assertEquals(10, $result['_yarn']['metadata']['cacheKey']);
    }

    public function testParsePreservesYarnChecksum(): void
    {
        $content = <<<YAML
__metadata:
  version: 8

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10/abc123def456
  languageName: node
  linkType: hard
YAML;

        $packageJson = [
            'name' => 'project',
            'version' => '1.0.0',
            'dependencies' => ['lodash' => '^4.17.0'],
        ];

        $result = $this->parser->parse($content, $packageJson);

        // Find the lodash package
        $lodashLocation = null;
        foreach ($result['packages'] as $location => $entry) {
            if (str_ends_with($location, 'lodash')) {
                $lodashLocation = $location;
                break;
            }
        }

        if ($lodashLocation !== null) {
            $lodash = $result['packages'][$lodashLocation];
            $this->assertArrayHasKey('_yarn', $lodash);
            $this->assertEquals('10/abc123def456', $lodash['_yarn']['checksum']);
        }
    }

    // ===== Dependencies Conversion Tests =====

    public function testConvertsDependenciesToNpmFormat(): void
    {
        $content = <<<YAML
__metadata:
  version: 8

"express@npm:^4.0.0":
  version: 4.18.2
  resolution: "express@npm:4.18.2"
  dependencies:
    debug: "npm:^4.0.0"
    accepts: "npm:~1.3.8"
  languageName: node
  linkType: hard

"debug@npm:^4.0.0":
  version: 4.3.4
  resolution: "debug@npm:4.3.4"
  languageName: node
  linkType: hard
YAML;

        $packageJson = [
            'name' => 'project',
            'version' => '1.0.0',
            'dependencies' => ['express' => '^4.0.0'],
        ];

        $result = $this->parser->parse($content, $packageJson);

        // Find express package
        $expressEntry = null;
        foreach ($result['packages'] as $location => $entry) {
            if (str_ends_with($location, 'express')) {
                $expressEntry = $entry;
                break;
            }
        }

        if ($expressEntry !== null && isset($expressEntry['dependencies'])) {
            // Dependencies should have npm: prefix stripped
            $this->assertArrayHasKey('debug', $expressEntry['dependencies']);
            $this->assertEquals('^4.0.0', $expressEntry['dependencies']['debug']);
        }
    }

    // ===== Root Package Tests =====

    public function testRootPackageCreatedFromPackageJson(): void
    {
        $content = <<<YAML
__metadata:
  version: 8
YAML;

        $packageJson = [
            'name' => 'my-awesome-app',
            'version' => '2.5.0',
            'dependencies' => ['lodash' => '^4.0.0'],
            'devDependencies' => ['jest' => '^29.0.0'],
        ];

        $result = $this->parser->parse($content, $packageJson);

        $this->assertArrayHasKey('', $result['packages']);
        $root = $result['packages'][''];
        $this->assertEquals('my-awesome-app', $root['name']);
        $this->assertEquals('2.5.0', $root['version']);
        $this->assertEquals(['lodash' => '^4.0.0'], $root['dependencies']);
        $this->assertEquals(['jest' => '^29.0.0'], $root['devDependencies']);
    }

    // ===== Serialization Tests =====

    public function testSerializeBasicStructure(): void
    {
        $normalized = [
            'name' => 'project',
            'version' => '1.0.0',
            'lockfileVersion' => 3,
            'packages' => [
                '' => ['name' => 'project', 'version' => '1.0.0'],
                'node_modules/lodash' => [
                    'version' => '4.17.21',
                ],
            ],
            '_yarn' => [
                'metadata' => ['version' => 8, 'cacheKey' => 10],
            ],
        ];

        $output = $this->parser->serialize($normalized, $normalized);

        // Should start with header comment
        $this->assertStringStartsWith('# This file is generated', $output);

        // Should contain metadata
        $this->assertStringContainsString('__metadata:', $output);
        $this->assertStringContainsString('version: 8', $output);
        $this->assertStringContainsString('cacheKey: 10', $output);

        // Should contain package entry
        $this->assertStringContainsString('lodash@npm:', $output);
    }

    public function testSerializePreservesChecksum(): void
    {
        $normalized = [
            'name' => 'project',
            'version' => '1.0.0',
            'lockfileVersion' => 3,
            'packages' => [
                '' => ['name' => 'project', 'version' => '1.0.0'],
                'node_modules/lodash' => [
                    'version' => '4.17.21',
                    '_yarn' => [
                        'checksum' => '10/abc123',
                    ],
                ],
            ],
            '_yarn' => [
                'metadata' => ['version' => 8],
            ],
        ];

        $output = $this->parser->serialize($normalized, $normalized);

        $this->assertStringContainsString('checksum:', $output);
    }

    // ===== Edge Cases =====

    public function testParseEmptyYarnLock(): void
    {
        $content = <<<YAML
__metadata:
  version: 8
YAML;

        $result = $this->parser->parse($content, []);

        $this->assertEquals(3, $result['lockfileVersion']);
        $this->assertArrayHasKey('packages', $result);
    }

    public function testParseWithoutPackageJson(): void
    {
        $content = <<<YAML
__metadata:
  version: 8

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  languageName: node
  linkType: hard
YAML;

        // Parse without package.json
        $result = $this->parser->parse($content, []);

        $this->assertEquals('', $result['name']);
        $this->assertEquals('0.0.0', $result['version']);
    }

    public function testInvalidYarnLockThrowsException(): void
    {
        $this->expectException(LockfileException::class);

        // A plain string parsed as YAML returns a string, not an array
        // This should trigger the "Invalid yarn.lock format" exception
        $content = "just a plain string without any YAML structure";

        $this->parser->parse($content, []);
    }

    // ===== Multi-Descriptor Tests =====

    public function testParseMultipleDescriptorsForSameResolution(): void
    {
        // In yarn.lock, multiple descriptors can point to the same resolution
        $content = <<<YAML
__metadata:
  version: 8

"lodash@npm:^4.0.0, lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  languageName: node
  linkType: hard
YAML;

        $packageJson = [
            'name' => 'project',
            'version' => '1.0.0',
            'dependencies' => ['lodash' => '^4.17.0'],
        ];

        $result = $this->parser->parse($content, $packageJson);

        // Should successfully parse despite multiple descriptors
        $this->assertArrayHasKey('packages', $result);
    }

    // ===== Protocol Handling Tests =====

    public function testSkipsWorkspaceProtocol(): void
    {
        $content = <<<YAML
__metadata:
  version: 8

"@yarnpkg/core@workspace:^":
  version: 0.0.0-use.local
  resolution: "@yarnpkg/core@workspace:packages/yarnpkg-core"
  languageName: unknown
  linkType: soft
YAML;

        $packageJson = [
            'name' => 'project',
            'version' => '1.0.0',
            'devDependencies' => ['@yarnpkg/core' => 'workspace:^'],
        ];

        $result = $this->parser->parse($content, $packageJson);

        // Workspace dependencies should not appear as node_modules entries
        $hasWorkspaceDep = false;
        foreach ($result['packages'] as $location => $entry) {
            if (str_contains($location, '@yarnpkg/core')) {
                $hasWorkspaceDep = true;
            }
        }

        // This is expected behavior - workspace deps are local, not in node_modules
        $this->assertFalse($hasWorkspaceDep);
    }
}
